version: '3.8'
name: pg3t
services:
  pg3t-db:
    image: postgres:15.4
    restart: unless-stopped
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pokemongen3teambuilderdb
    networks:
      - pg3t-network
  pg3t-server:
    image: pg3t-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    environment:
      - ENV_NAME=dev
      - PORT=3333
      - DATABASE_URL=postgresql://postgres:123@pg3t-db:5432/pokemongen3teambuilderdb?schema=public
    ports:
      - 3333:3333
    depends_on:
      - pg3t-db
    networks:
      - pg3t-network
networks:
  pg3t-network:
