import z from 'zod';
import { AbilitySchema, MoveSchema, PokemonSchema } from '../../prisma/zod';

// These types and schemas are combinations of the basic schemas generated by zod-prisma-types
// Pokemon
export const PokemonWithAbilitiesSchema = PokemonSchema.merge(z.object({ abilities: z.array(AbilitySchema) }));
export const PokemonWithAbilitiesAndLearnsetSchema = PokemonWithAbilitiesSchema.merge(z.object({ learnset: z.array(MoveSchema) }));

export type PokemonWithAbilities = z.infer<typeof PokemonWithAbilitiesSchema>;
export type PokemonWithAbilitiesAndLearnset = z.infer<typeof PokemonWithAbilitiesAndLearnsetSchema>;
