version: '3.8'
services:
  dev-db:
    image: postgres:15.4
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pokemongen3teambuilderdb
    networks:
      - pokemon-gen3-teambuilder
  test-db:
    image: postgres:15.4
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pokemongen3teambuilderdb
    networks:
      - pokemon-gen3-teambuilder
networks:
  pokemon-gen3-teambuilder:
