version: '3.8'
name: pg3t-dev
services:
  dev-db:
    image: postgres:15.4
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pokemongen3teambuilderdb
    networks:
      - pg3t-dev-network
networks:
  pg3t-dev-network:
