export const enum TypesNames {
  normal = 'normal',
  ice = 'ice',
  ghost = 'ghost',
  dark = 'dark',
  grass = 'grass',
  electric = 'electric',
  steel = 'steel',
  ground = 'ground',
  fighting = 'fighting',
  bug = 'bug',
  poison = 'poison',
  rock = 'rock',
  water = 'water',
  flying = 'flying',
  fire = 'fire',
  dragon = 'dragon',
  psychic = 'psychic',
  empty = 'empty',
}

export const commonClasseses = 'w-14 capitalize text-foreground';
export const typeClassNames = {
  bug: 'bg-bug',
  dark: 'bg-dark',
  dragon: 'bg-dragon',
  electric: 'bg-electric',
  fighting: 'bg-fighting',
  fire: 'bg-fire',
  flying: 'bg-flying',
  ghost: 'bg-ghost',
  grass: 'bg-grass',
  ground: 'bg-ground',
  ice: 'bg-ice',
  normal: 'bg-normal',
  poison: 'bg-poison',
  psychic: 'bg-psychic',
  rock: 'bg-rock',
  steel: 'bg-steel',
  water: 'bg-water',
  empty: 'bg-empty',
};
